#!/usr/bin/env zsh
emulate -L zsh
setopt no_unset err_exit
#setopt xtrace

echo "ZSH version is $ZSH_VERSION"

if [[ ! -d .git ]] {
	echo "This must be run from the root of the dotfiles repository" >&2
	exit 1
}

fpath+=( $PWD/.zsh/functions )
autoload -U syntax-check
git ls-files -z -- '.zsh*' | while { read -rd $'\0' file } {
	# TODO: loading ztcp (`zmodload -F zsh/net/tcp`) causes the process to get a
	# SIGKILL. Maybe a bpf program?
	if [[ $file == .zsh/functions/znc ]] continue
	if [[ $file =~ \.zsh/help/.* ]] continue
	echo -n "Syntax checking $file... "
	syntax-check $file
	echo "OK"
}
