format = "$username$hostname$shlvl$directory$time$jobs$status$character"

# Don't print a newline at the start of the prompt
add_newline = false

[directory]
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"depot/google3" = "³"
"google3" = "³"
"waymo" = ""
"third_party/car" = "tp"
"simulator/queue" = "simqueue"
"sim/queue" = "simqueue"

[hostname]
format = "[$hostname]($style) in "

[username]
disabled = true

[status]
disabled = false

[package]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[time]
disabled = false

[line_break]
disabled = true

[shlvl]
# Breaks screen sessions (for some reason)
disabled = true

[c]
disabled = true

[battery]
disabled = true
